apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-api
  template:
    metadata:
      labels:
        app: rails-api
    spec:
      containers:
        - name: rails-api
          image: gialexa/my_own_app_on_k8s:latest
          ports:
            - containerPort: 3000
          env: # Move env here
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-secret-key
                  key: SECRET_KEY_BASE
---
apiVersion: v1
kind: Service
metadata:
  name: rails-api-service
spec:
  selector:
    app: rails-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
